export const EVENT_GROUPS = {
  MEMBERS: [
    "MEMBER_JOIN",
    "MEMBER_JOIN_WITH_PRIOR_RECORDS",
    "MEMBER_LEAVE",
    "MEMBER_NICK_CHANGE",
    "MEMBER_RESTORE",
    "MEMBER_ROLE_ADD",
    "MEMBER_ROLE_CHANGES",
    "MEMBER_ROLE_REMOVE",
    "MEMBER_USERNAME_CHANGE",
  ],
  MESSAGES: [
    "MESSAGE_DELETE",
    "MESSAGE_DELETE_AUTO",
    "MESSAGE_DELETE_BARE",
    "MESSAGE_DELETE_BULK",
    "MESSAGE_EDIT",
  ],
  VOICE: [
    "VOICE_CHANNEL_FORCE_DISCONNECT",
    "VOICE_CHANNEL_FORCE_MOVE",
    "VOICE_CHANNEL_JOIN",
    "VOICE_CHANNEL_LEAVE",
    "VOICE_CHANNEL_MOVE",
  ],
  SERVER: [
    "ROLE_CREATE",
    "ROLE_DELETE",
    "ROLE_UPDATE",
    "EMOJI_CREATE",
    "EMOJI_DELETE",
    "EMOJI_UPDATE",
    "CHANNEL_CREATE",
    "CHANNEL_DELETE",
    "CHANNEL_UPDATE",
    "STAGE_INSTANCE_CREATE",
    "STAGE_INSTANCE_DELETE",
    "STAGE_INSTANCE_UPDATE",
    "STICKER_CREATE",
    "STICKER_DELETE",
    "STICKER_UPDATE",
    "THREAD_CREATE",
    "THREAD_DELETE",
    "THREAD_UPDATE",
  ],
  AUTOMOD: [
    "AUTOMOD_ACTION",
    "CENSOR",
    "MESSAGE_SPAM_DETECTED",
    "OTHER_SPAM_DETECTED",
    "SET_ANTIRAID_AUTO",
    "SET_ANTIRAID_USER",
  ],
  MODERATION: [
    "CLEAN",
    "CASE_CREATE",
    "CASE_DELETE",
    "CASE_UPDATE",
    "MASSBAN",
    "MASSMUTE",
    "MASSUNBAN",
    "MEMBER_BAN",
    "MEMBER_FORCEBAN",
    "MEMBER_KICK",
    "MEMBER_MUTE",
    "MEMBER_MUTE_EXPIRED",
    "MEMBER_MUTE_REJOIN",
    "MEMBER_NOTE",
    "MEMBER_SOFTBAN",
    "MEMBER_TIMED_BAN",
    "MEMBER_TIMED_MUTE",
    "MEMBER_TIMED_UNBAN",
    "MEMBER_TIMED_UNMUTE",
    "MEMBER_UNBAN",
    "MEMBER_UNMUTE",
    "MEMBER_WARN",
  ],
  OTHERS: [
    "BOT_ALERT",
    "COMMAND",
    "DM_FAILED",
    "POSTED_SCHEDULED_MESSAGE",
    "SCHEDULED_MESSAGE",
    "SCHEDULED_REPEATED_MESSAGE",
    "REPEATED_MESSAGE",
  ],
};

export const DEFAULT_AUTOMOD = {
  automod: {
    config: {
      rules: {
        basic_rule: {
          triggers: [
            { message_spam: { amount: 10, within: "10s" } },
            { message_spam: { amount: 3, within: "5s" } },
            { sticker_spam: { amount: 5, within: "10s" } },
            { mention_spam: { amount: 5, within: "10s" } },
            { emoji_spam: { amount: 3, within: "5s" } },
            { attachment_spam: { amount: 3, within: "10s" } },
            { match_invites: {} },
          ],
          actions: {
            clean: true,
            mute: {
              duration: "5m",
              reason: 'Auto-muted for spam',
            },
          },
        },
      },
    },
  },
};
